import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='flex justify-center'>
      <div className="flex flex-col min-w-full min-h-screen">
        
        {children}

      </div>
    </main>
  );
}
